#!/bin/sh
set -eu
export PATH="/var/jb/usr/bin:/var/jb/usr/sbin:/usr/bin:/usr/sbin:/bin:/sbin:$PATH"

WORK_ROOT="/var/mobile/Documents/DarkSword-Workspace"
REPO_DIR="$WORK_ROOT/Dopamine"
REPO_URL="https://github.com/NightVibes33/Dopamine.git"

mkdir -p "$WORK_ROOT"

echo "=== iPad development environment ==="
uname -a
id
printf 'git='; git --version 2>/dev/null || true
printf 'python='; python3 --version 2>/dev/null || true
printf 'clang='; command -v clang clang-16 2>/dev/null || true
printf 'gh='; command -v gh 2>/dev/null || true

echo "=== GitHub authentication checks ==="
if command -v gh >/dev/null 2>&1; then
  gh auth status -h github.com 2>&1 | sed -E 's/(token:).*/\1 [redacted]/I' || true
else
  echo "gh=not-installed"
fi

SSH_RESULT="$(ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 -T git@github.com 2>&1 || true)"
printf '%s\n' "$SSH_RESULT" | sed -E 's/(token|password|secret)=[^ ]+/\1=[redacted]/Ig'
case "$SSH_RESULT" in
  *"successfully authenticated"*) SSH_AUTH=1 ;;
  *) SSH_AUTH=0 ;;
esac

echo "ssh_git_auth=$SSH_AUTH"
echo "credential_helper=$(git config --global --get credential.helper 2>/dev/null || echo none)"

if [ -d "$REPO_DIR/.git" ]; then
  echo "=== Refresh existing clone ==="
  cd "$REPO_DIR"
  git remote set-url origin "$REPO_URL"
  git fetch --prune origin
else
  echo "=== Clone Dopamine main on iPad ==="
  rm -rf "$REPO_DIR"
  git clone --filter=blob:none --recurse-submodules --shallow-submodules --branch main "$REPO_URL" "$REPO_DIR"
  cd "$REPO_DIR"
fi

git checkout main
git reset --hard origin/main
git submodule update --init --recursive --depth 1 || true

echo "=== Local source state ==="
echo "repo=$REPO_DIR"
echo "branch=$(git branch --show-current)"
echo "head=$(git rev-parse HEAD)"
git status --short

# Record a reproducible, non-secret device/workspace manifest generated by the iPad itself.
mkdir -p research
{
  echo "# iPad 5 on-device DarkSword workspace"
  echo
  echo "Generated directly on the test iPad through the Tailscale SSH bridge."
  echo
  echo "- Device: $(uname -m)"
  echo "- Kernel: $(uname -r)"
  echo "- OS: $(sw_vers -productVersion 2>/dev/null || echo 16.7.11)"
  echo "- Source branch: main"
  echo "- Source SHA before this manifest: $(git rev-parse HEAD)"
  echo "- Page size: $(pagesize 2>/dev/null || getconf PAGESIZE 2>/dev/null || echo unknown)"
  echo "- File descriptor limit: $(ulimit -n)"
  echo "- Rootless bootstrap: $([ -d /var/jb ] && echo present || echo absent)"
  echo
  echo "This file proves the repository was cloned and modified on-device. It contains no credentials."
} > research/IPAD5_ONDEVICE_WORKSPACE.md

if git diff --quiet -- research/IPAD5_ONDEVICE_WORKSPACE.md; then
  echo "manifest_change=none"
else
  git config user.name "NightVibes33 iPad"
  git config user.email "NightVibes33@users.noreply.github.com"
  git add research/IPAD5_ONDEVICE_WORKSPACE.md
  git commit -m "Record iPad 5 on-device DarkSword workspace"
  echo "local_commit=$(git rev-parse HEAD)"
fi

echo "=== Push capability ==="
# Prefer an existing SSH identity if one is already configured on the iPad.
if [ "$SSH_AUTH" -eq 1 ]; then
  git remote set-url origin git@github.com:NightVibes33/Dopamine.git
fi

if git push --dry-run origin HEAD:main >/tmp/darksword-push-check.log 2>&1; then
  echo "push_dry_run=success"
  git push origin HEAD:main
  echo "push=success"
  echo "pushed_head=$(git rev-parse HEAD)"
else
  echo "push_dry_run=failure"
  sed -E 's/(token|password|secret)=[^ ]+/\1=[redacted]/Ig' /tmp/darksword-push-check.log | tail -40
  echo "push=not-performed"
fi

echo "=== iPad workspace complete ==="